import {
  HomePage,
  CollabPage,
  Ohjesaannot,
  EventPage,
  Fuksit,
  HallitusPage,
  AktiiviPage,
  PeriaatteetPage,
  DokumenttiPage,
  KansainvalisyysPage,
  KunniagalleriaPage,
  SalaisuudetPage,
  SaannotPage,
  RekisteriselostePage,
  YhteydenottoPage,
  JasenEdutPage,
  RekrytPage,
  KerhotoimintaPage,
  HakijatPage,
  PrevHalli,
  VujuPage,
  NotFound,
} from './pages'

export const pageRoutes = [
  { path: '/', element: <HomePage />, seoKey: 'home' },
  { path: '/tapahtumat', element: <EventPage />, seoKey: 'events' },
  { path: '/yhteistyot', element: <CollabPage />, seoKey: 'collaboration' },
  { path: '/fuksit', element: <Fuksit />, seoKey: 'freshmen' },
  { path: '/hallitus', element: <HallitusPage />, seoKey: 'board' },
  { path: '/ohjesaannot', element: <Ohjesaannot />, seoKey: 'guidelines' },
  { path: '/aktiivit', element: <AktiiviPage />, seoKey: 'activeMembers' },
  { path: '/periaatteet', element: <PeriaatteetPage />, seoKey: 'principles' },
  {
    path: '/yhdenvertaisuus',
    element: <PeriaatteetPage to="/periaatteet" replace />,
    seoKey: 'principles',
  },
  { path: '/vujuetiketti', element: <VujuPage />, seoKey: 'annualFestivities' },
  { path: '/dokumentit', element: <DokumenttiPage />, seoKey: 'documents' },
  {
    path: '/kansainvalisyys',
    element: <KansainvalisyysPage />,
    seoKey: 'international',
  },
  {
    path: '/kunniagalleria',
    element: <KunniagalleriaPage />,
    seoKey: 'hallOfFame',
  },
  { path: '/salaisuudet', element: <SalaisuudetPage />, seoKey: 'secrets' },
  { path: '/saannot', element: <SaannotPage />, seoKey: 'rules' },
  { path: '/seloste', element: <RekisteriselostePage />, seoKey: 'privacy' },
  { path: '/lomakkeet', element: <YhteydenottoPage />, seoKey: 'forms' },
  { path: '/jasenedut', element: <JasenEdutPage />, seoKey: 'memberBenefits' },
  { path: '/rekryt', element: <RekrytPage />, seoKey: 'recruitment' },
  { path: '/kerhotoiminta', element: <KerhotoimintaPage />, seoKey: 'clubs' },
  { path: '/hakijalle', element: <HakijatPage />, seoKey: 'applicants' },
  {
    path: '/entiset-hallitukset',
    element: <PrevHalli />,
    seoKey: 'formerBoards',
  },
  { path: '*', element: <NotFound />, seoKey: 'notFound', noIndex: true },
]